### ISSUE TITLE
Infografia 

### ISSUE THREAD

**Issue by Arlet04** [SistemasTecTlaxiaco/actividad-1-infografia-Arlet04-1#1]
[Infografia Jeanette Arlet Salazar Nicolás.pdf](https://github.com/SistemasTecTlaxiaco/actividad-1-infografia-Arlet04-1/files/14249640/Infografia.Jeanette.Arlet.Salazar.Nicolas.pdf)

**Comment by josealfredo79** [comment]
Calificacion 20...
